#!/bin/bash
#SBATCH --account=akara
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=00:10:00
#SBATCH --error=%J.err
#SBATCH --output=%J.out
#SBATCH --job-name=entropy
#SBATCH --mem-per-cpu=10000

script=$1

python3 $script $2 $3 $4
##
